//import fitness from "../../Assets/img/fitness.png";
import pick_dice_game from "../../Assets/img/pick_dice_game.png";
//import ai from "../../Assets/img/gener8.png";
// import mov from "../../Assets/img/movieApp.png";
// import cocktail from "../../Assets/img/cocktaily.png";

export const ProjectsData = [
  {
    id: 1,
    feats: [
      "2 Players",
      "Game declears winner after any of the 2 Players dice picks 20 and above first",
    ],
    name: "Dice Pick Game",
    det: "This is a Dice Picking Game built with HTML, CSS and Javacript",
    code: "https://github.com/ayeniayodeji2009/pick_dice_game",
    live: "https://pick-dice-game.vercel.app/",
    image: pick_dice_game,
    stack: ["HTML", "CSS", "Javascript"],
  },
//   {
//     id: 2,
//     feats: ["Search for excercises according to bodypart", "Show more details about an excercise when clicked", "Watch Youtube videos on how to do the excercise"],
//     name: "Fitness App",
//     det: "A React based app that displays gym execrises with corresponding gifs and a details page. React, SCSS, WebAPIs",
//     code: "https://github.com/mo-renike/fitness",
//     live: "https://fitnessexercises.netlify.app",
//     image: fitness,
//     stack: ["React", "Scss", "WebAPIs"],
//   },
//   {
//     id: 3,
//     feats: [
//       "Generate an image based on a prompt",
//       "Share generated image",
//       "View all the images generated by different users",
//     ],
//     name: "Ai image generator",
//     det: "A React based app that generates images using the OpenAI API.",
//     live: "https://ai-image-generator-alpha.vercel.app/",
//     code: "https://github.com/mo-renike/Ai_image_generator",
//     image: ai,
//     stack: ["React", "Tailwind", "OpenAI API", "GPT-3", "Firebase", "Cloudinary"],
//   },

  // {
  //   id: 3,
  //feats: "",
  //   name: "Edutech Website",
  //   det: "Implementation of a figma website design using HTML, Sass and Vanilla Javascript",
  //   code: "https://github.com/mo-renike/edutech",
  //   live: "https://mo-renike.github.io/edutech/",
  //   img: edutech,
  // },
  // {
  //   id: 5,
  //   name: "Movies Review App",
  //   det: "A Javacsript based app that displays movies with corresponding image and a details preview using HTML5, CSS3, Vanilla Javascript, WebAPIs",
  //   code: "https://github.com/mo-renike/Movie-App",
  //   live: "https://mo-renike.github.io/Movie-App/",
  //   img: mov,
  // },
  // {
  //   id: 5,
  //   name: "Cocktail App",
  //   det: "A Javacsript based app that displays cocktails with corresponding image and a details page using HTML5, CSS3, Vanilla Javascript, WebAPIs",
  //   code: "https://github.com/mo-renike/cocktail-app",
  //   live: "https://cocktaily1.netlify.app/",
  //   img: cocktail,
  // },
  // {
  //   id: 4,
  //   name: "50 Javascript Projects",
  //   det: "A collection of 50 projects in 50 days using pure HTML, CSS and Javascript",
  //   code: "https://github.com/mo-renike/50Javascript-projects",
  //   live: "https://mo-renike.github.io/50Javascript-projects/",
  //   img: proj,
  // },
];
